In [4]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.metrics import r2_score


# 1. Cargar

df = pd.read_csv("kc_house_data.csv")

print("Dimensiones:", df.shape)
df.head()

Dimensiones: (21613, 21)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [6]:
# Variable dependiente a predecir
y = df['price']

# Variables independientes
X = df[[
    'bedrooms',
    'bathrooms',
    'sqft_living',
    'sqft_lot',
    'floors',
    'waterfront',
    'view',
    'condition',
    'grade',
    'sqft_basement',
    'yr_built',
    'yr_renovated',
    'lat',
    'long',
    'sqft_living15',
    'sqft_lot15'
]]

In [8]:
# 2. Agregar columna de unos

X_mat = np.column_stack((np.ones(len(X)), X))

# Convertir a matrices numpy
X_mat = np.array(X_mat)
y_mat = np.array(y)

# 3. Beta = (X'X)^(-1)X'Y


beta = np.linalg.inv(X_mat.T @ X_mat) @ X_mat.T @ y_mat

coeficientes = pd.DataFrame({
    'Variable':['Intercepto'] + list(X.columns),
    'Coeficiente':beta
})

coeficientes

         Variable   Coeficiente
0      Intercepto -3.686262e+07
1        bedrooms -3.415167e+04
2       bathrooms  4.216171e+04
3     sqft_living  1.795138e+02
4        sqft_lot  1.274163e-01
5          floors  7.606881e+02
6      waterfront  5.878472e+05
7            view  4.942923e+04
8       condition  3.103180e+04
9           grade  9.721937e+04
10  sqft_basement -3.285873e+01
11       yr_built -2.456276e+03
12   yr_renovated  2.153244e+01
13            lat  5.610605e+05
14           long -1.170209e+05
15  sqft_living15  2.743120e+01
16     sqft_lot15 -3.932879e-01

In [10]:
# 4. Predicciones

y_pred = X_mat @ beta


# 5. R²

r2 = r2_score(y, y_pred)

n = len(y)
k = X.shape[1]

r2_adj = 1 - ((1-r2)*(n-1)/(n-k-1))

print("R² =", round(r2,4))
print("R² Ajustado =", round(r2_adj,4))

R² = 0.6954
R² Ajustado = 0.6952

In [12]:
# 6. Reporte estadístico


X_sm = sm.add_constant(X)

modelo = sm.OLS(y, X_sm).fit()

print(modelo.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.695
Model:                            OLS   Adj. R-squared:                  0.695
Method:                 Least Squares   F-statistic:                     3082.
Date:                Tue, 30 Jun 2026   Prob (F-statistic):               0.00
Time:                        08:29:37   Log-Likelihood:            -2.9476e+05
No. Observations:               21613   AIC:                         5.895e+05
Df Residuals:                   21596   BIC:                         5.897e+05
Df Model:                          16
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const         -3.686e+07    1.6e+06    -23.105      0.000      -4e+07   -3.37e+07
bedrooms      -3.415e+04   1903.178    -17.945      0.000   -3.79e+04   -3.04e+04
bathrooms      4.216e+04   3276.490     12.868      0.000    3.57e+04    4.86e+04
sqft_living     179.5138      3.693     48.608      0.000     172.275     186.752
sqft_lot          0.1274      0.048      2.640      0.008       0.033       0.222
floors          760.6881   3605.813      0.211      0.833   -6306.972    7828.348
waterfront     5.878e+05   1.75e+04     33.625      0.000    5.54e+05    6.22e+05
view           4.943e+04   2146.437     23.028      0.000    4.52e+04    5.36e+04
condition      3.103e+04   2353.444     13.186      0.000    2.64e+04    3.56e+04
grade          9.722e+04   2166.897     44.866      0.000     9.3e+04    1.01e+05
sqft_basement   -32.8587      4.390     -7.484      0.000     -41.464     -24.253
yr_built      -2456.2763     72.580    -33.842      0.000   -2598.539   -2314.014
yr_renovated     21.5324      3.680      5.850      0.000      14.318      28.746
lat            5.611e+05   1.05e+04     53.197      0.000     5.4e+05    5.82e+05
long           -1.17e+05    1.2e+04     -9.755      0.000   -1.41e+05   -9.35e+04
sqft_living15    27.4312      3.457      7.935      0.000      20.655      34.207
sqft_lot15       -0.3933      0.074     -5.330      0.000      -0.538      -0.249
==============================================================================
Omnibus:                    18537.369   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1882235.907
Skew:                           3.617   Prob(JB):                         0.00
Kurtosis:                      48.142   Cond. No.                     5.85e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.85e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [14]:
# 7. Valores p


pvalues = pd.DataFrame({
    'Variable': modelo.pvalues.index,
    'p_value': modelo.pvalues.values
})

pvalues.sort_values('p_value')

         Variable        p_value
13            lat   0.000000e+00
3     sqft_living   0.000000e+00
9           grade   0.000000e+00
11       yr_built  1.133690e-244
6      waterfront  1.197866e-241
0           const  1.060633e-116
7            view  6.019411e-116
1        bedrooms   1.750369e-71
8       condition   1.508236e-39
2       bathrooms   9.386464e-38
14           long   1.962849e-22
15  sqft_living15   2.203813e-15
10  sqft_basement   7.479166e-14
12   yr_renovated   4.973978e-09
16     sqft_lot15   9.936970e-08
4        sqft_lot   8.299415e-03
5          floors   8.329192e-01

In [18]:
# Variables con p > 0.05

variables_significativas = modelo.pvalues[
    modelo.pvalues < 0.05
].index.tolist()

variables_significativas.remove('const')

print("Variables significativas:")
print(variables_significativas)

Variables significativas:
['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'waterfront', 'view', 'condition', 'grade', 'sqft_basement', 'yr_built', 'yr_renovated', 'lat', 'long', 'sqft_living15', 'sqft_lot15']

In [20]:
# 8. Modelo final


X_final = df[variables_significativas]

X_final_sm = sm.add_constant(X_final)

modelo_final = sm.OLS(y, X_final_sm).fit()

print(modelo_final.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.695
Model:                            OLS   Adj. R-squared:                  0.695
Method:                 Least Squares   F-statistic:                     3287.
Date:                Tue, 30 Jun 2026   Prob (F-statistic):               0.00
Time:                        08:29:59   Log-Likelihood:            -2.9476e+05
No. Observations:               21613   AIC:                         5.895e+05
Df Residuals:                   21597   BIC:                         5.897e+05
Df Model:                          15
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const         -3.692e+07   1.57e+06    -23.516      0.000      -4e+07   -3.38e+07
bedrooms      -3.416e+04   1902.164    -17.961      0.000   -3.79e+04   -3.04e+04
bathrooms      4.234e+04   3164.159     13.381      0.000    3.61e+04    4.85e+04
sqft_living     179.6412      3.643     49.307      0.000     172.500     186.782
sqft_lot          0.1272      0.048      2.636      0.008       0.033       0.222
waterfront     5.879e+05   1.75e+04     33.626      0.000    5.54e+05    6.22e+05
view           4.944e+04   2145.243     23.048      0.000    4.52e+04    5.36e+04
condition        3.1e+04   2347.988     13.202      0.000    2.64e+04    3.56e+04
grade          9.726e+04   2158.970     45.048      0.000     9.3e+04    1.01e+05
sqft_basement   -33.2686      3.937     -8.450      0.000     -40.986     -25.551
yr_built      -2453.0853     70.985    -34.558      0.000   -2592.221   -2313.950
yr_renovated     21.5718      3.676      5.869      0.000      14.367      28.776
lat            5.613e+05   1.05e+04     53.524      0.000    5.41e+05    5.82e+05
long          -1.174e+05   1.19e+04     -9.879      0.000   -1.41e+05   -9.41e+04
sqft_living15    27.3428      3.431      7.969      0.000      20.617      34.068
sqft_lot15       -0.3938      0.074     -5.340      0.000      -0.538      -0.249
==============================================================================
Omnibus:                    18531.230   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1879952.363
Skew:                           3.616   Prob(JB):                         0.00
Kurtosis:                      48.114   Cond. No.                     5.76e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.76e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [22]:
# 9. Ecuación final


coef = modelo_final.params

print("\nECUACIÓN FINAL:\n")

ecuacion = f"Precio = {coef.iloc[0]:.2f}"

for variable, valor in coef.iloc[1:].items():
    ecuacion += f" + ({valor:.4f})*{variable}"

print(ecuacion)

ECUACIÓN FINAL:

Precio = -36922319.02 + (-34164.4966)*bedrooms + (42341.0922)*bathrooms + (179.6412)*sqft_living + (0.1272)*sqft_lot + (587854.2714)*waterfront + (49444.0313)*view + (30998.1762)*condition + (97258.3187)*grade + (-33.2686)*sqft_basement + (-2453.0853)*yr_built + (21.5718)*yr_renovated + (561297.2535)*lat + (-117371.0868)*long + (27.3428)*sqft_living15 + (-0.3938)*sqft_lot15